name: test_m
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  youtube_explode_dart: ^2.3.0
  dio: ^5.4.1
  cached_network_image: ^3.3.1
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  http: ^1.2.0
  path: ^1.9.0
  palette_generator: ^0.3.3
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "revix.logo.png"
  min_sdk_android: 21

